{
 "title": "Test",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Eden",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(jvm_memory_pool_bytes_used{pool=\"Eden Space\"}[2s])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Eden Max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Eden Space\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Survivor",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(jvm_memory_pool_bytes_used{pool=\"Survivor Space\"}[2s])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Survivor Max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Survivor Space\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Tenured",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(jvm_memory_pool_bytes_used{pool=\"Tenured Gen\"}[2s])",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Tenured Max",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_max{pool=\"Tenured Gen\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Number of Young Collections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{gc=\"Copy\"}[2s])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Number of Old Collections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{gc=\"MarkSweepCompact\"}[2s])",
     "legendFormat": "{{gc}}"
    }
   ]
  }
 ]
}