apiVersion: v1
kind: Service
metadata:
  name: jbang-service
spec:
  selector:
    app: jbang
  ports:
  - name: jmx-exporter
    port: 8081
    targetPort: 8081
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: jbang-pod
  labels:
    app: jbang
spec:
  containers:
  - name: jbang
    image: jbangdev/jbang-action:0.83.1
    imagePullPolicy: IfNotPresent
    ports:
    - name: jmx-exporter
      containerPort: 8081
      protocol: TCP
    env:
    - name: INPUT_SCRIPT
      value: '/scripts/GenerationalGCTest.java'
    - name: INPUT_JBANGARGS
      value: '-D=com.sun.management.jmxremote -D=com.sun.management.jmxremote.host=0.0.0.0 -D=com.sun.management.jmxremote.port=9010 -D=com.sun.management.jmxremote.local.only=false -D=com.sun.management.jmxremote.authenticate=false -D=com.sun.management.jmxremote.ssl=false --javaagent=io.prometheus.jmx:jmx_prometheus_javaagent:0.16.1=8081:/scripts/prometheus-exporter-config.yaml'
    volumeMounts:
    - name: jbang-volume
      mountPath: /scripts/GenerationalGCTest.java
      subPath: GenerationalGCTest.java
    - name: jbang-volume
      mountPath: /scripts/prometheus-exporter-config.yaml
      subPath: prometheus-exporter-config.yaml
  volumes:
  - name: jbang-volume
    configMap:
      name: jbang-cm          
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: jbang-cm
data:
  GenerationalGCTest.java: |-
    //JAVA_OPTIONS -XX:+UseSerialGC -Xlog:gc*
    //JAVA_OPTIONS -XX:-UseAdaptiveSizePolicy
    //JAVA_OPTIONS -Xms64m -Xmx64m 
    //JAVA_OPTIONS -XX:NewSize=10m -XX:SurvivorRatio=3

    public class GenerationalGCTest {
      public static void main(String... args) throws Exception {

        int size = (int)(1024*1024 * 0.9); // Almost 1KB

        while( true ){
          Thread.sleep( 10_000 );
          new java.util.Random().nextBytes( new byte[size] );
        }//while

      }//main

    }//class

  prometheus-exporter-config.yaml: |-
    startDelaySeconds: 0
    hostPort: 127.0.0.1:9010
    ssl: false
