apiVersion: v1
kind: Service
metadata:
  name: jbang-service
spec:
  selector:
    app: jbang
  ports:
  - name: jmx-exporter
    port: 8081
    targetPort: 8081
    protocol: TCP
  - name: jbang-jmx
    port: 9010
    targetPort: 9010
    protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: jbang-pod
  labels:
    app: jbang
spec:
  containers:
  - name: jbang
    image: jbangdev/jbang-action:0.87.0
    imagePullPolicy: IfNotPresent
    ports:
    - name: jmx-exporter
      containerPort: 8081
      protocol: TCP
    - name: jbang-jmx
      containerPort: 9010
      protocol: TCP
    env:
    - name: INPUT_SCRIPT
      value: '/scripts/GenerationalGCTest.java'
    - name: INPUT_JBANGARGS
      value: >-
        -D=com.sun.management.jmxremote 
        -D=com.sun.management.jmxremote.host=0.0.0.0
        -D=com.sun.management.jmxremote.port=9010
        -D=com.sun.management.jmxremote.local.only=false
        -D=com.sun.management.jmxremote.authenticate=false
        -D=com.sun.management.jmxremote.ssl=false
        --javaagent=io.prometheus.jmx:jmx_prometheus_javaagent:0.16.1=8081:/scripts/prometheus-exporter-config.yaml
    volumeMounts:
    - name: jbang-volume
      mountPath: /scripts/GenerationalGCTest.java
      subPath: GenerationalGCTest.java
    - name: jbang-volume
      mountPath: /scripts/prometheus-exporter-config.yaml
      subPath: prometheus-exporter-config.yaml
  volumes:
  - name: jbang-volume
    configMap:
      name: jbang-cm
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: jbang-cm
data:
  GenerationalGCTest.java: |-
    //JAVA_OPTIONS -Xint
    //JAVA_OPTIONS -XX:+UseSerialGC -Xlog:gc*
    //JAVA_OPTIONS -XX:-UseAdaptiveSizePolicy
    //JAVA_OPTIONS -Xms8m -Xmx8m 
    //JAVA_OPTIONS -Xmn3m

    public class GenerationalGCTest {

      static class MyObject{
        double a;
      }

      public static void main(String... args) throws Exception {
        while( args.length > -1 ){
          Thread.sleep(1_000);
          new MyObject();
        }

      }//main

    }//class

  prometheus-exporter-config.yaml: |-
    startDelaySeconds: 0
    hostPort: 127.0.0.1:9010
    ssl: false
