apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
spec:
  selector:
    app: prometheus
  ports:
  - name: dashboard
    port: 9090
    targetPort: 9090
    protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: prometheus-pod
  labels:
    app: prometheus
spec:
  containers:
  - name: prometheus
    image: prom/prometheus:v2.31.1
    imagePullPolicy: IfNotPresent
    ports:
    - name: dashboard
      containerPort: 9090
      protocol: TCP
    volumeMounts:
    - name: prometheus-volume
      mountPath: /etc/prometheus/prometheus.yml
      subPath: prometheus.yml
  volumes:
  - name: prometheus-volume
    configMap:
      name: prometheus-cm
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: prometheus-cm
data:
  prometheus.yml: |-
    global:
      scrape_interval: 1s
    scrape_configs:    
    - job_name: jbang-job
      static_configs:
      - targets: ['jbang-service:8081']
